version: "3.9"
services:
  api:
    image: ghcr.io/casc-vel/module-evaluations:dev
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["8080:8080"]
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Db: Host=db;Username=app;Password=app;Database=app
      Redis__Connection: redis:6379
    depends_on: [db, redis]
    restart: unless-stopped
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
  redis:
    image: redis:7
