name: Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
    validations:
      required: true
