name: Publish Contracts NuGet Packages

on:
  push:
    tags:
      - 'contracts-v*'
  workflow_dispatch:

jobs:
  publish-nugets:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true
          cache-dependency-path: |
            **/*.csproj
            Directory.Packages.props

      - name: Authenticate GitHub Packages for restore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget update source "github-casc-vel" \
            --configfile ./nuget.config \
            --username "${{ github.actor }}" \
            --password "$GITHUB_TOKEN" \
            --store-password-in-clear-text

      - name: Restore dependencies
        run: dotnet restore slnf/contracts.slnf

      - name: Build projects
        run: dotnet build slnf/contracts.slnf --configuration Release --no-restore

      - name: Pack NuGet packages
        run: |
          for csproj in $(find src/contracts -name '*.csproj'); do
            dotnet pack "$csproj" --configuration Release --no-build --output ./nupkgs
          done

      - name: Push packages to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for nupkg in ./nupkgs/*.nupkg; do
            dotnet nuget push "$nupkg" --source "github-casc-vel" --api-key "$GITHUB_TOKEN" --skip-duplicate
          done
